
version: "3.7"
services:
    nginxmain:
        build:
            context: ./docker/nginxmain/
            dockerfile: Dockerfile.nginxmain
        ports:
            - 8083:80
        depends_on:
            - nginx1
            - nginx2
            - nginx3
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - "phpsocket:/var/run"
    nginx1:
        build:
            context: ./docker/nginx1/
            dockerfile: Dockerfile.nginx1
        depends_on:
            - fpm
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - "phpsocket:/var/run"
    nginx2:
        build:
            context: ./docker/nginx2/
            dockerfile: Dockerfile.nginx2
        depends_on:
            - fpm
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - "phpsocket:/var/run"
    nginx3:
        build:
            context: ./docker/nginx3/
            dockerfile: Dockerfile.nginx3
        depends_on:
            - fpm
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - "phpsocket:/var/run"
    fpm:
        build:
            context: ./docker/fpm
            dockerfile: Dockerfile.fpm
        depends_on:
            - postgres
            - phpcli
            - rabbitmq
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - ./config-php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./www/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./zz-docker/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - "phpsocket:/var/run"
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            RabbitMQ_USER: ${RabbitMQ_USER}
            RabbitMQ_PASSWORLD: ${RabbitMQ_PASSWORLD}
    phpcli:
        build:
            context: ./docker/phpcli/
            dockerfile: Dockerfile.phpcli
        command: "php /var/www/html/ReceiverQueueRpcServer.php"
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            RabbitMQ_USER: ${RabbitMQ_USER}
            RabbitMQ_PASSWORLD: ${RabbitMQ_PASSWORLD}
        restart: on-failure
        depends_on:
            - rabbitmq
            - postgres

    postgres:
        build:
            context: ./docker/postgres/
            dockerfile: Dockerfile.postgres
        ports:
            - "6543:5432"
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:${DB_PATH_CONTAINER}
        restart: unless-stopped

    pgadmin:
        build:
            context: ./docker/pgadmin/
            dockerfile: Dockerfile.pgadmin
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        restart: unless-stopped
    rabbitmq:
        build:
            context: ./docker/rabbitmq
            dockerfile: Dockerfile.rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            RabbitMQ_USER: ${RabbitMQ_USER}
            RabbitMQ_PASSWORLD: ${RabbitMQ_PASSWORLD}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
volumes:
  postgres-data:
  phpsocket:
  rabbitmq-data:
